add dark mode & more readable line and brigade buttons
DomeQdev/zbiorkom.live-v3 pull request #6
Opened 2022-08-05 18:33 UTC by AKurushimi

dark mode w/ os preference check and saving to localstorage + more readable buttons

2022-08-05 18:34 UTC, DomeQdev commented
Omg squash

2022-08-05 18:35 UTC, DomeQdev requested changes
Zmiane w brygadach wypierdolic, co jedynie czarne tlo zamiast bialego

2022-08-05 18:37 UTC, DomeQdev requested changes
I dark mode do settings a nie do headera

2022-08-05 18:39 UTC, AKurushimi commented
> Zmiane w brygadach wypierdolic, co jedynie czarne tlo zamiast bialego

bedzie nieczytelne

2022-08-05 19:45 UTC, DomeQdev approved these changes

2022-08-05 19:46 UTC, DomeQdev requested changes
Cum

2022-08-06 12:11 UTC, DomeQdev requested changes
Kod jest okropny, muszę sam go naprawić na podstawie twoich zmian jak wrócę do domu

2022-08-07 12:21 UTC, DomeQdev commented
Nie doslownie okropny ale nie estetyczny

2022-08-10 11:32 UTC, DomeQdev approved these changes

2022-08-17 19:27 UTC, DomeQdev commented
#9

2022-08-17 19:27 UTC, closed without merging